server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.232.166.228:3306/toy?characterEncoding=UTF-8&serverTimezone=UTC
    username: deker
    password: deker123!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql query pretty option
        default_batch_fetch_size: 1000 # fetch join in query
  messages:
    basename: classpath:/i18n/messages, classpath:/i18n/errors
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false