server:
  port: 8080

logging:
  level:
    kr.toyauction: debug # project logging
    org:
      springframework:
        transaction: warn # spring transaction logging
        web: warn # spring web logging
        security: warn # spring security logging
        orm:
          jpa: warn # spring orm jpa logging
      hibernate:
        SQL: OFF # hibernate sql logging
        type.descriptor.sql: OFF # DDL 시 입력된 실제 Value 값을 확인할려면 trace 으로 사용
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://toydb.c38ary0y4f5o.ap-northeast-2.rds.amazonaws.com/toy?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${db_password}
  jpa:
    open-in-view: false # 지연 로딩을 Controller 까지 확장 하는것 을 금지 한다. 자세한 내용은 OSIV 패턴 참고
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # mysql DB engine
    hibernate:
      ddl-auto: update # DDL AUTO 전략
    properties:
      hibernate:
        format_sql: true # sql query pretty option
        default_batch_fetch_size: 1000 # fetch join in query
    show-sql: false # logging 과 중복되므로 해당옵션은 false
  data:
    web:
      pageable:
        default-page-size: 20 # page default size
  servlet:
    multipart:
      enabled: true # file upload true
      max-file-size: 1024MB # single file max size
      max-request-size: 1024MB # total file request max size
  messages:
    basename: classpath:/i18n/messages, classpath:/i18n/errors # messages 경로
  web:
    resources:
      add-mappings: false # url 으로 resources 접근 여부